# Generated by Django 5.1.2 on 2024-10-31 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0002_url_created_at_alter_url_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='kLiUW', max_length=5, unique=True),
        ),
    ]
