# Generated by Django 5.1.2 on 2024-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.CharField(max_length=200, unique=True)),
                ('short_url', models.CharField(default='YegVE', max_length=5, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
