# Generated by Django 5.1.2 on 2024-10-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='3WZOE', max_length=5, unique=True),
        ),
    ]
