# Generated by Django 5.1.2 on 2024-10-31 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_alter_url_short_url_alter_url_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='short_url',
            field=models.CharField(default='9yTLn', max_length=5, unique=True),
        ),
    ]
